---
AWSTemplateFormatVersion: 2010-09-09

Description: Stack to deploy a highly available, elastic, scalable WordPress worker environment.

Metadata:

  Authors:
    Description: Bipul Ranjan (bipul@webjack.in)
  License:
    Description: ''

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: General AWS
      Parameters:
        - EC2KeyName
        - SshAccessCidr
        - AdminEmail
        - WPDomainName
        - UseCloudFrontBoolean
        - CloudFrontAcmCertificate
    - Label:
        default: Network
      Parameters:
        - Vpc
        - NumberOfAZs
        - PublicSubnet
        - WebSubnet
        - DataSubnet
        - WebSecurityGroup
        - EfsSecurityGroup
        - PublicAlbSecurityGroup
        - PublicAlbAcmCertificate
    - Label:
        default: File System Tier
      Parameters:
        - EfsPerformanceMode
        - EfsEncrpytedBoolean
        - EfsCmk
        - EfsGrowth
        - EfsGrowthInstanceType
    - Label:
        default: Database Tier
      Parameters:
        - DatabaseClusterEndpointAddress
        - DatabaseMasterUsername
        - DatabaseMasterPassword
        - DatabaseName
    - Label:
        default: Web Tier
      Parameters:
        - PHPVersion
        - PHPIniOverride
        - WebInstanceType
        - WebAsgMax
        - WebAsgMin
    - Label:
        default: WordPress
      Parameters:
        - WPVersion
        - WPTitle
        - WPAdminUsername
        - WPAdminPassword
        - WPDirectory
        - WPLocale
    ParameterLabels:
      CloudFrontAcmCertificate:
        default: CloudFront Certificate ARN
      DatabaseMasterUsername:
        default: DB Master Username
      DatabaseMasterPassword:
        default: DB Master Password
      DatabaseName:
        default: DB Name
      DatabaseClusterEndpointAddress:
        default: Database Cluster address
      EfsCmk:
        default: AWS KMS CMK for EFS
      EfsEncrpytedBoolean:
        default: Encrpyted EFS?
      EfsGrowth:
        default: Add dummy data (GiB)
      EfsGrowthInstanceType:
        default: Instance Type
      EfsPerformanceMode:
        default: EFS Performance Mode
      WebSubnet:
        default: VPC Web Subnet
      DataSubnet:
        Description: VPC Data Subnet
      PublicSubnet:
        Description: VPC Public Subnet
      WebSecurityGroup:
        Description: Web Security Group.
      EfsSecurityGroup:
        Description: EFS Security Group.
      PublicAlbSecurityGroup:
        Description: Public Alb Security Group
      Vpc:
        Description: Virtual Private Cloud
      EC2KeyName:
        default: EC2 Key Pair
      PHPIniOverride:
        default: AWS php.ini Overrides
      PublicAlbAcmCertificate:
        default: ALB Certificate ARN
      UseCloudFrontBoolean:
        default: CDN (CloudFront)
      WebAsgMax:
        default: Web ASG Max
      WebAsgMin:
        default: Web ASG Min
      WebInstanceType:
        default: Web Tier Instance Type
      WPTitle:
        default: Site Title
      WPAdminUsername:
        default: Admin Username
      WPAdminPassword:
        default: Admin Password
      AdminEmail:
        default: Email Address
      WPDirectory:
        default: Site Directory
      WPDomainName:
        default: Site Domain
      WPLocale:
        default: Language Code
      WPVersion:
        default: WordPress Version
      NumberOfAZs:
        default: Number of Availability Zones
      PHPVersion:
        default: PHP Version
      

Parameters:

  CloudFrontAcmCertificate:
    AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: '[ Optional ] The AWS Certification Manager certificate ARN for the CloudFront distribution certificate - this certificate should be created in the us-east-1 (N. Virginia) region and must reference the WordPress domain name you use below.'
    Type: String
  DatabaseMasterUsername:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The Amazon RDS master username.
    ConstraintDescription: Must contain only alphanumeric characters (minimum 8; maximum 16).
    MaxLength: 16
    MinLength: 8
    Type: String
  DatabaseMasterPassword:
    AllowedPattern: ^([a-zA-Z0-9`~!#$%^&*()_+,\\-])*$
    ConstraintDescription: Must be letters (upper or lower), numbers, spaces, and these special characters `~!#$%^&*()_+,-
    Description: The Amazon RDS master password. Letters, numbers, spaces, and these special characters `~!#$%^&*()_+,-
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String
  DatabaseName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The Amazon RDS master database name.
    Type: String
  EfsEncrpytedBoolean:
    AllowedValues:
      - true
      - false
    Default: false
    Description: Create an encrypted Amazon EFS file system.
    Type: String
  EfsCmk:
    AllowedPattern: ^$|(arn:aws:kms:)([a-z0-9/:-])*([a-z0-9])$
    ConstraintDescription: Must be an existing ARN for an AWS KMS CMK.
    Description: '[ Optional ] The AWS KMS customer-managed CMK ARN to encrypt & decrypt the EFS file system.'
    Type: String
  EfsGrowth:
    Default: 0
    ConstraintDescription: Must be an integer.
    Description: Amount of dummy data (GiB) to add to the file system (max 6144 GiB). Amazon EFS storage charges apply.
    MaxValue: 6144
    MinValue: 0
    Type: Number
  EfsGrowthInstanceType:
    AllowedValues:
    - t2.nano 
    - t2.micro 
    - t2.small 
    - t2.medium 
    - t2.large 
    - t2.xlarge 
    - t2.2xlarge 
    - m3.medium 
    - m3.large 
    - m3.xlarge 
    - m3.2xlarge 
    - m4.large 
    - m4.xlarge 
    - m4.2xlarge 
    - m4.4xlarge 
    - m4.10xlarge 
    - m4.16xlarge 
    - m5.large 
    - m5.xlarge 
    - m5.2xlarge 
    - m5.4xlarge 
    - m5.12xlarge 
    - m5.24xlarge 
    - c3.large 
    - c3.xlarge 
    - c3.2xlarge 
    - c3.4xlarge 
    - c3.8xlarge 
    - c4.large 
    - c4.xlarge 
    - c4.2xlarge 
    - c4.4xlarge 
    - c4.8xlarge 
    - c5.large 
    - c5.xlarge 
    - c5.2xlarge 
    - c5.4xlarge 
    - c5.9xlarge 
    - c5.18xlarge
    - r3.large 
    - r3.xlarge 
    - r3.2xlarge 
    - r3.4xlarge 
    - r3.8xlarge 
    - r4.large 
    - r4.xlarge 
    - r4.2xlarge 
    - r4.4xlarge 
    - r4.8xlarge 
    - r4.16xlarge 
    - x1.16xlarge 
    - x1.32xlarge 
    - x1e.xlarge 
    - x1e.2xlarge 
    - x1e.4xlarge 
    - x1e.8xlarge 
    - x1e.16xlarge 
    - x1e.32xlarge
    - d2.xlarge 
    - d2.2xlarge 
    - d2.4xlarge 
    - d2.8xlarge 
    - h1.2xlarge 
    - h1.4xlarge 
    - h1.8xlarge 
    - h1.16xlarge 
    - i2.xlarge 
    - i2.2xlarge 
    - i2.4xlarge 
    - i2.8xlarge 
    - i3.large 
    - i3.xlarge 
    - i3.2xlarge 
    - i3.4xlarge 
    - i3.8xlarge 
    - i3.16xlarge
    - f1.2xlarge 
    - f1.16xlarge 
    - g2.2xlarge 
    - g2.8xlarge 
    - g3.4xlarge 
    - g3.8xlarge 
    - g3.16xlarge 
    - p2.xlarge 
    - p2.8xlarge 
    - p2.16xlarge 
    - p3.2xlarge 
    - p3.8xlarge 
    - p3.16xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: t2.nano
    Description: The Amazon EC2 instance type that adds data to the file system.
    Type: String
  EfsPerformanceMode:
    AllowedValues:
      - generalPurpose
      - maxIO
    Default: generalPurpose
    Description: Select the performance mode of the file system.
    Type: String
  EC2KeyName:
    ConstraintDescription: Must be letters (upper or lower), numbers, and special characters.
    Description: Name of an EC2 KeyPair. Your bastion & Web instances will launch with this KeyPair.
    Type: AWS::EC2::KeyPair::KeyName
  PHPIniOverride:
    Description: Full Amazon S3 https path to a php.ini override file (e.g. https://s3.amazonaws.com/aws-refarch/wordpress/latest/bits/20-aws.ini)
    Type: String
    Default: https://s3.amazonaws.com/aws-refarch/wordpress/latest/bits/20-aws.ini
  PHPVersion:
    AllowedValues:
    - 5.5
    - 5.6
    - 7.0
    Default: 7.0
    Description: The version of PHP to install.
    Type: String 
  PublicAlbAcmCertificate:
    AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: '[ Optional ] The AWS Certification Manager certificate ARN for the ALB certificate - this certificate should be created in the region you wish to run the ALB and must reference the WordPress domain name you use below.'
    Type: String
  UseCloudFrontBoolean:
    AllowedValues:
      - true
      - false
    Default: true
    Description: Specifies whether a CloudFront Distribution should be created to serve the WordPress website content.
    Type: String
  WebAsgMax:
    AllowedPattern: ^((?!0$)[1-2]?[0-9]|30)$
    ConstraintDescription: Must be a number between 1 and 30.
    Default: 10
    Description: Specifies the maximum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebAsgMin:
    AllowedPattern: ^([0-0]?[0-9]|10)$
    ConstraintDescription: Must be a number between 0 and 10.
    Default: 2
    Description: Specifies the minimum number of EC2 instances in the Web Autoscaling Group.
    Type: String
  WebInstanceType:
    AllowedValues:
      - t2.nano 
      - t2.micro 
      - t2.small 
      - t2.medium 
      - t2.large 
      - t2.xlarge 
      - t2.2xlarge 
      - m3.medium 
      - m3.large 
      - m3.xlarge 
      - m3.2xlarge 
      - m4.large 
      - m4.xlarge 
      - m4.2xlarge 
      - m4.4xlarge 
      - m4.10xlarge 
      - m4.16xlarge 
      - m5.large 
      - m5.xlarge 
      - m5.2xlarge 
      - m5.4xlarge 
      - m5.12xlarge 
      - m5.24xlarge 
      - c3.large 
      - c3.xlarge 
      - c3.2xlarge 
      - c3.4xlarge 
      - c3.8xlarge 
      - c4.large 
      - c4.xlarge 
      - c4.2xlarge 
      - c4.4xlarge 
      - c4.8xlarge 
      - c5.large 
      - c5.xlarge 
      - c5.2xlarge 
      - c5.4xlarge 
      - c5.9xlarge 
      - c5.18xlarge
      - r3.large 
      - r3.xlarge 
      - r3.2xlarge 
      - r3.4xlarge 
      - r3.8xlarge 
      - r4.large 
      - r4.xlarge 
      - r4.2xlarge 
      - r4.4xlarge 
      - r4.8xlarge 
      - r4.16xlarge 
      - x1.16xlarge 
      - x1.32xlarge 
      - x1e.xlarge 
      - x1e.2xlarge 
      - x1e.4xlarge 
      - x1e.8xlarge 
      - x1e.16xlarge 
      - x1e.32xlarge
      - d2.xlarge 
      - d2.2xlarge 
      - d2.4xlarge 
      - d2.8xlarge 
      - h1.2xlarge 
      - h1.4xlarge 
      - h1.8xlarge 
      - h1.16xlarge 
      - i2.xlarge 
      - i2.2xlarge 
      - i2.4xlarge 
      - i2.8xlarge 
      - i3.large 
      - i3.xlarge 
      - i3.2xlarge 
      - i3.4xlarge 
      - i3.8xlarge 
      - i3.16xlarge
      - f1.2xlarge 
      - f1.16xlarge 
      - g2.2xlarge 
      - g2.8xlarge 
      - g3.4xlarge 
      - g3.8xlarge 
      - g3.16xlarge 
      - p2.xlarge 
      - p2.8xlarge 
      - p2.16xlarge 
      - p3.2xlarge 
      - p3.8xlarge 
      - p3.16xlarge
    ConstraintDescription: Must be a valid Amazon EC2 instance type.
    Default: t2.nano
    Description: The Amazon EC2 instance type for your web instances.
    Type: String
  AdminEmail:
    AllowedPattern: ^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$
    Description: The admin email address for WordPress and AWS notifications.
    Type: String
  WPAdminPassword:
    AllowedPattern: ^([a-zA-Z0-9`~!#$%^&*()_+,\\-])*$
    ConstraintDescription: Must be letters (upper or lower), numbers, spaces, and these special characters `~!#$%^&*()_+,-    
    Description: The WordPress admin password. Letters, numbers, spaces, and these special characters `~!#$%^&*()_+,-
    Type: String
    NoEcho: true
  WPAdminUsername:
    AllowedPattern: ^([a-zA-Z0-9])([a-zA-Z0-9_-])*([a-zA-Z0-9])$
    Description: The WordPress admin username.
    Type: String
  WPDirectory:
    AllowedPattern: ^([a-zA-Z0-9])([a-zA-Z0-9_-])*([a-zA-Z0-9])$
    Description: The WordPress site directory.
    Type: String
  WPDomainName:
    AllowedPattern: ^$|(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$
    Description: '[ Optional ] The main domain name of the WordPress site (e.g. example.com).'
    Type: String
  WPLocale:
    Description: "The main language of the WordPress site, as per https://codex.WordPress.org/Installing_WordPress_in_Your_Language. The default is 'en_GB'."
    Type: String
    Default: en_GB
  WPTitle:
    Default: This is a new WordPress site on Amazon Web Services
    AllowedPattern: ^([a-zA-Z0-9])([a-zA-Z0-9 _-]*)([a-zA-Z0-9])$
    Description: The WordPress website title.
    Type: String
  NumberOfAZs:
    AllowedValues:
    - 2
    - 3
    - 4
    - 5
    - 6
    Default: 3
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.
    Type: Number
  WPVersion:
    AllowedValues:
      - latest
      - nightly
      - 4.5
      - 4.6
      - 4.7
      - 4.8
      - 4.9
    Default: latest
    Description: The WordPress version (make sure this version is compatible with the PHP version selected above).
    Type: String
  WebSecurityGroup:
    Description: Select the Amazon security group.
    Type: AWS::EC2::SecurityGroup::Id   
  WebSubnet:
    Description: Select existing subnets.
    Type: List<AWS::EC2::Subnet::Id>
  EfsSecurityGroup:
    Description: Select the Amazon security group.
    Type: AWS::EC2::SecurityGroup::Id   
  DataSubnet:
    Description: Select existing subnets.
    Type: List<AWS::EC2::Subnet::Id>
  PublicAlbSecurityGroup:
    Description: Select the Amazon security group.
    Type: AWS::EC2::SecurityGroup::Id   
  PublicSubnet:
    Description: Select existing subnets.
    Type: List<AWS::EC2::Subnet::Id>
  DatabaseClusterEndpointAddress:
    Description: The RDS cluster endpoint address.
    Type: String
  Vpc:
    Description: Select an existing Vpc
    Type: AWS::EC2::VPC::Id

Conditions:

  AvailableAWSRegion:
    !Or [
      !Equals [ !Ref 'AWS::Region', ap-southeast-2 ],
      !Equals [ !Ref 'AWS::Region', eu-central-1 ],
      !Equals [ !Ref 'AWS::Region', eu-west-1 ],
      !Equals [ !Ref 'AWS::Region', us-east-1 ],
      !Equals [ !Ref 'AWS::Region', us-east-2 ],
      !Equals [ !Ref 'AWS::Region', us-west-2 ]
    ]
  DeployCloudFront: !And
    - !Equals [ true, !Ref UseCloudFrontBoolean ]
    - !Condition AvailableAWSRegion

Resources:

  cloudfront:
    Condition: DeployCloudFront
    DependsOn: [ publicalb, web ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudFrontAcmCertificate:
          !Ref CloudFrontAcmCertificate
        PublicAlbDnsName:
          !GetAtt [ publicalb, Outputs.PublicAlbDnsName ]
        WPDomainName:
          !Ref WPDomainName
      TemplateURL: https://s3.amazonaws.com/webjack/wordpress/latest/templates/aws-refarch-wordpress-04-cloudfront.yaml
  efsfilesystem:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EncrpytedBoolean:
          !Ref EfsEncrpytedBoolean
        Cmk:
          !Ref EfsCmk
        EC2KeyName:
          !Ref EC2KeyName
        SecurityGroup:
          !Ref EfsSecurityGroup
        Growth:
          !Ref EfsGrowth
        InstanceType:
          !Ref EfsGrowthInstanceType
        NumberOfSubnets:
          !Ref NumberOfAZs  
        PerformanceMode:
          !Ref EfsPerformanceMode
        Subnet:
          !Join
            - ','
            - !Ref DataSubnet
      TemplateURL: https://s3.amazonaws.com/webjack/wordpress/latest/templates/aws-refarch-wordpress-03-efsfilesystem.yaml
  publicalb:
    Condition: AvailableAWSRegion
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NumberOfSubnets:
          !Ref NumberOfAZs
        Subnet:
          !Join
            - ','
            - !Ref PublicSubnet
        PublicAlbAcmCertificate:
          !Ref PublicAlbAcmCertificate
        PublicAlbSecurityGroup:
          !Ref PublicAlbSecurityGroup
        Vpc:
          !Ref Vpc
      TemplateURL: https://s3.amazonaws.com/webjack/wordpress/latest/templates/aws-refarch-wordpress-07-workeralb.yaml
  web:
    Condition: AvailableAWSRegion
    DependsOn: [ efsfilesystem, publicalb ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseClusterEndpointAddress:
          !Ref DatabaseClusterEndpointAddress
        DatabaseMasterUsername:
          !Ref DatabaseMasterUsername
        DatabaseMasterPassword:
          !Ref DatabaseMasterPassword
        DatabaseName:
          !Ref DatabaseName
        ElasticFileSystem:
          !GetAtt [ efsfilesystem, Outputs.ElasticFileSystem ]
        EC2KeyName:
          !Ref EC2KeyName
        NumberOfSubnets:
          !Ref NumberOfAZs
        PHPIniOverride:
          !Ref PHPIniOverride
        PHPVersion:
          !Ref PHPVersion
        PublicAlbTargetGroupArn:
          !GetAtt [ publicalb, Outputs.PublicAlbTargetGroupArn ]
        PublicAlbHostname:
          !GetAtt [ publicalb, Outputs.PublicAlbHostname ]
        SslCertificate:
          !GetAtt [ publicalb, Outputs.SslCertificate ]
        WebAsgMax:
          !Ref WebAsgMax
        WebAsgMin:
          !Ref WebAsgMin
        WebInstanceType:
          !Ref WebInstanceType
        WebSecurityGroup:
          !Ref WebSecurityGroup
        Subnet:
          !Join
            - ','
            - !Ref WebSubnet
        WPAdminEmail:
          !Ref AdminEmail
        WPAdminPassword:
          !Ref WPAdminPassword
        WPAdminUsername:
          !Ref WPAdminUsername
        WPDirectory:
          !Ref WPDirectory
        WPDomainName:
          !Ref WPDomainName
        WPLocale:
          !Ref WPLocale
        WPTitle:
          !Ref WPTitle
        WPVersion:
          !Ref WPVersion
      TemplateURL: https://s3.amazonaws.com/webjack/wordpress/latest/templates/aws-refarch-wordpress-04-web.yaml

Outputs:

  WPSiteUrl:
    Description: The URL of the WordPress site
    Value: !If [ DeployCloudFront, !GetAtt [ cloudfront, Outputs.DnsHostname ], !GetAtt [ publicalb, Outputs.PublicAlbHostname ] ]
